### ISSUE TITLE
[Documentation] Leave a note for those manually installing mods

### ISSUE THREAD

**Issue by YuLun-bili** [klyte45/CS2ModsRepository#1]
To help other weirdos (such as me, who just don't want to install Overwolf & Thunderstore for some unexplainable reasons) to install your mods manually.

The archive uploaded to Thunderstore cannot be simply thrown into game folder, one have to change file path of `plugins\UI` to `UI` inside each mods to ensure mod loading properly.

And thank you again for your amazing work :)

**Comment by klyte45** [comment]
Hi!

I confess I don't know how to do without the executable... I might try it after and add here - or if anyone have this knowledge and wants to add here, feel free to clone this repository, do the changes and then open a merge request here

**Comment by pikachukaki** [comment]
so how to install this mod? Simply drop everything in ~\BepInEx\plugins or ~\BepInEx\plugins\Klyte45-ExtendedTransportManager-0.0.1?

**Comment by YuLun-bili** [comment]
- Get mod archive from Thunderstore
- Unarchive the folder and it would possibly be named as `Klyte45-MODNAME-x.x.x`
- Inside you should find a folder `plugins`, `README.md`, `manifest.json`, `i18n.csv`, `icon.png`, some `.dll` and possibly a `.euis`
- Open folder `plugins`, cut/copy everything inside
- Back to directly under mod's folder (same place with those other files I just listed), paste files just cut/copied
- Delete folder `plugins`
- Now put the mod's folder to `BepInEx\plugins`, game should load with no errors

**Comment by pikachukaki** [comment]
> * Get mod archive from Thunderstore
> * Unarchive the folder and it would possibly be named as `Klyte45-MODNAME-x.x.x`
> * Inside you should find a folder `plugins`, `README.md`, `manifest.json`, `i18n.csv`, `icon.png`, some `.dll` and possibly a `.euis`
> * Open folder `plugins`, cut/copy everything inside
> * Back to directly under mod's folder (same place with those other files I just listed), paste files just cut/copied
> * Delete folder `plugins`
> * Now put the mod's folder to `BepInEx\plugins`, game should load with no errors

Yeah doing this stops some http errors but still there isn't any difference in the public transportation screen. 

Bepinex logs sawing that both plugins are loaded

**Comment by YuLun-bili** [comment]
press `Ctrl` + `Tab`, mod using a new screen overlays above game rather than directly modifying game's UI

**Comment by fleps** [comment]
> Hi!
> 
> I confess I don't know how to do without the executable... I might try it after and add here - or if anyone have this knowledge and wants to add here, feel free to clone this repository, do the changes and then open a merge request here

What you mean? To distribute here you just release a zip with the DLL and any other file you need for the mod inside it, and we just unzip into the `BepInEx/plugins folder`.
You can check other mods released on github, or this guide: https://github.com/optimus-code/Cities2Modding

I also prefer manual install instead of having to install another software on my computer considering in a few months all this is going to be obsolete / migrated to the official PDMods

**Comment by klyte45** [comment]
I believe this was answered here already. Anyway, I created some places to support at Discord and added the links in this repository. I'll keep everything there since it's easier to maintain, including the mods installation instructions.

Closing this
